services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: challenge
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      # I have chosen to use 8080 as the external port and left 8484 as the internal port, as it already was
      - "8080:8080"
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8080
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "./seeder && ./server"
